#+TITLE: DotFiles Config
Configuration files for linux and WSL environment

* Installation
- update apt.
- install yadm
- clone this repository with yadm
- open vim and type ":PlugInstall"
- install python3-pip
- with pip3 install pyvim
- for c++ syntax instally clang
* Other Packages Used
- zsh and oh-my-zsh (after installing add "source .zsh_defaults.sh" in zshrc
- gdb
- fzf
* WSL Troubleshooting
** wsltty Config
confing file should be place in:
username/AppData/Roaming/wsltty/config

** Allowing Windows Fonts
follow
https://x410.dev/cookbook/wsl/sharing-windows-fonts-with-wsl/
make sure you find the exact place the font is saved at.
fonts should be in ttf format.
** Allow Emacs Links
   follow this [[https://www.reddit.com/r/bashonubuntuonwindows/comments/70i8aa/making_emacs_on_wsl_open_links_in_windows_web/][comment]]
** Change Distribution
   to see distribution list type "wsl -l" in cmd
   to switch default use "wsl -s <distribution>"
** Packages not installing (signature failure)
   You need to temporarly set package-check-signature variable to nil then 
   install gnu-elpa-keyring-update.
   better possibilities in [[https://emacs.stackexchange.com/questions/233/how-to-proceed-on-package-el-signature-check-failure][here]].
   
