#+TITLE: DotFiles Config
#+DESCRIPTION: Configuration files for linux and WSL environment
 
* Installation
- update apt.
- install yadm
- clone this repository with yadm
- open vim and type ":PlugInstall"
- install python3-pip
- with pip3 install pyvim
- for c++ syntax instally clang
- install [[https://github.com/politza/pdf-tools#server-prerequisites][these packages]] for pdf-tools
* Some Notes
** Computer specific settings
- create DROPBOX_DIR environment variable 
** Dependicies
   - setuptools package for python
   - texlive-latex-extra and python-pygments for literate programming
* Other Packages Used
** Shell
   zsh and oh-my-zsh after installation add plugins git, fzf, tmux, vi-mode
   and source .zsh\under{}defaults.sh.
** other...
   - gdb
   - fzf
* WSL Troubleshooting
** wsltty Config
   confing file should be place in:
   username/AppData/Roaming/wsltty/config

** Allowing Windows Fonts
   follow [[https://x410.dev/cookbook/wsl/sharing-windows-fonts-with-wsl/][this]]
   make sure you find the exact place the font is saved at.
   fonts should be in ttf format.
** Allow Emacs Links
   follow this [[https://www.reddit.com/r/bashonubuntuonwindows/comments/70i8aa/making_emacs_on_wsl_open_links_in_windows_web/][comment]]
** Change Distribution
   to see distribution list 
   #+BEGIN_SRC cmd
   wsl -l
   #+END_SRC
   to switch default distribution 
   #+BEGIN_SRC cmd
   wsl -s <distribution>
   #+END_SRC
** Packages not installing (signature failure)
   You need to temporarly set package-check-signature variable to nil then 
   install gnu-elpa-keyring-update.
   Even better try this:
   #+BEGIN_SRC sh
   gpg --keyserver hkp://keyserver.ubuntu.com:80 --homedir ~/.emacs.d/elpa/gnupg --receive-keys 066DAFCB81E42C40
   #+END_SRC
   
* Emacs dependencies
- yapf
- jedi for completion
